// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhdphpktauuwauvbtljg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZHBocGt0YXV1d2F1dmJ0bGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjUyMDEsImV4cCI6MjA2MzEwMTIwMX0.Z_boKTihkdIGTyz8FVPliUlOoRYxK88xn-JJPuCAmoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);